### ISSUE TITLE
How to use on Linux?

### ISSUE THREAD

**Issue by m-j-w** [UUoocl/Transparent-Google-Slides#1]
Looking for such a feature since quite a while.
How would I use this on Linux? Any ideas how to start?

**Comment by UUoocl** [comment]
This app is created using Electron Fiddle.  I recommend downloading the [Electron Fiddle for Linux](https://www.electronjs.org/fiddle#downloads), then load the [Transparent Google Slides gist](https://gist.github.com/UUoocl/5c82968370559141be5ff3db5fa19486).

In the Electron Fiddle app there is a "Load Fiddle" button in the upper right.  Paste the Gist URL in the field next to the "Load Fiddle" button. 
![image](https://github.com/UUoocl/Transparent-Google-Slides/assets/99063397/7e3fa507-e670-48f8-a242-cf6afba99eb2)

**Transparent Google Slides gist URL**

https://gist.github.com/UUoocl/5c82968370559141be5ff3db5fa19486

I'm interested to know if it works, please share your results! Thanks

**Comment by m-j-w** [comment]
Ok. Struggling to get electron fiddle in general to run. Appears to be unrelated to your fiddle though.

```
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
[295480:0924/114216.574949:ERROR:ozone_platform_x11.cc(241)] Missing X server or $DISPLAY
[295480:0924/114216.574970:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.

Electron exited with code 1.
```

Manually setting the DISPLAY variable, e.g. with
```
export DISPLAY=:1              # Yes, it is :1
electron-fiddle
```
does result in a correctly set variable, but this doesn't seem to be forwarded to the child processes, i.e. the electron child process being launched.
Weird...

**Comment by m-j-w** [comment]
Interesting. Seems to launch when run manually from the console directly with electron.

Loaded and saved the fiddle locally, then
```
npm install --save-dev electron
npm start
```

**Comment by m-j-w** [comment]
Okay. Tested automatic scene changing and that appears to work nicely. Really cool !

Had some issues with the OBS websocket connection, though. Seems like only "localhost" works regardless what's shown in OBS as server IP. Might also be a local issue, of course.

Feel free to close this issue.

**Comment by UUoocl** [comment]
Happy to hear you figured out how to get this working in Linux.  Thanks for opening the issue and sharing the solution!
